library(dplyr)
library(data.table)
data <- read.table("household_power_consumption.txt",header = TRUE,sep=";",stringsAsFactors = FALSE)
library(lubridate)
data <- mutate(data, Date=as.Date(data$Date,format="%d/%m/%Y"))
data1 <- filter(data,Date=="2007-02-01")
data2 <- filter(data,Date=="2007-02-02")
DATA <- merge(data1,data2,all = TRUE)
png(filename = "plot1.png")
hist(as.numeric(DATA$Global_active_power),col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()