library(dplyr)
library(data.table)
data <- read.table("household_power_consumption.txt",sep=";",header = TRUE,stringsAsFactors = FALSE)
library(lubridate)
data <- mutate(data,Date=as.Date(data$Date,format="%d/%m/%Y"))
data <- mutate(data,datetime=paste(data$Date,data$Time,sep=" "))
data1 <- filter(data,Date=="2007-02-01")
data2 <- filter(data,Date=="2007-02-02")
DATA <- merge(data1,data2,all=TRUE)
x <- strptime(DATA$datetime,"%Y-%m-%d %H:%M:%S")

png(filename = "plot4.png")
par(mfrow=c(2,2),mar=c(5,5,2,1))
with(DATA,plot(x,as.numeric(DATA$Global_active_power),type = "l",xlab = "",ylab = "Global Active Power"))
with(DATA,plot(x,as.numeric(DATA$Voltage),type = "l",xlab = "datetime",ylab = "Voltage"))
plot(x,as.numeric(DATA$Sub_metering_1),type="l",xlab="",ylab = "Energy sub metering")
lines(x,as.numeric(DATA$Sub_metering_2),type = "l",col="red")
lines(x,as.numeric(DATA$Sub_metering_3),type = "l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = 1,lwd = 2.5,col=c("black","red","blue"),bty = "o")
with(DATA,plot(x,as.numeric(DATA$Global_reactive_power),type = "l",xlab = "datetime",ylab = "Global_reactive_power"))
dev.off()