library(dplyr)
library(data.table)
data <- read.table("household_power_consumption.txt",header = TRUE,sep=";",stringsAsFactors = FALSE)
library(lubridate)
data <- mutate(data, Date=as.Date(data$Date,format="%d/%m/%Y"))
data <- mutate(data,datetime=paste(data$Date,data$Time,sep=" "))
data1 <- filter(data,Date=="2007-02-01")
data2 <- filter(data,Date=="2007-02-02")
DATA <- merge(data1,data2,all = TRUE)
x <- strptime(DATA$datetime,"%Y-%m-%d %H:%M:%S")
png(filename = "plot2.png")
with(DATA,plot(x,as.numeric(DATA$Global_active_power),type = "l",xlab = "",ylab = "Global Active Power (kilowatts)"))
dev.off()
